name: DevSkim

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  devskim:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run DevSkim scanner
        uses: microsoft/DevSkim-Action@v1
        with:
          directory: .                 # scan seluruh repo
          output: devskim-results.sarif

      - name: Verify DevSkim output exists
        run: |
          if [ ! -f devskim-results.sarif ]; then
            echo "DevSkim did not generate SARIF file!"
            exit 1
          fi

      - name: Upload DevSkim results to Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: devskim-results.sarif
